### ISSUE TITLE
Avoid interrupting default commands/events

### ISSUE THREAD

**Issue by jengjeng** [jengjeng/aural-coding-vscode#3]
Now, the program defines the keys to activate the audio playback function in the package.json.

https://github.com/jengjeng/aural-coding-vscode/blob/18a710c534574b87a08cae68f588fa7f74415fc5/package.json#L31-L41

However, it has interrupted default commands/events of visual studio code and other plugins.
For example. If you press `Backspace` button it should remove 1 character in your text editor and play the sound. But for now, It only plays the sound and can't remove the character.

We need to fix it to not interrupting with the other commands/events.

**Comment by st-schneider** [comment]
yep, totally interferes with all other extensions that have shortcuts, especially the vim extension which also has different modes.

**Comment by jengjeng** [comment]
This issue has fixed. Please update to version 1.1.0.
